<h3>Task 01:Your objective is to manually compute the slope (M) and y-intercept (C) using Ordinary Least Squares Linear Regression.Once determined, apply these values to predict the price when the vegetable weight is 6.5

In [1]:
!pip install pandas
!pip install sklearn
!pip install matplotlib
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression

Requirement already satisfied: pandas in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.

  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sharmin akter\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
df=pd.read_excel('vegetable.xlsx')
df.head()

   Weight  Price
0     2.0   35.0
1     4.0   60.0
2     5.0   20.0
3     3.0   50.0
4     6.0   50.0

In [4]:
df.shape

(8, 2)

In [5]:
df['Price'] = pd.to_numeric(df['Price'],errors='coerce')
df['Weight'] = pd.to_numeric(df['Weight'],errors='coerce')

In [6]:
x = df['Weight']
y = df['Price']
mean_x=np.mean(x)
mean_y=np.mean(y)

In [7]:
df.describe()

         Weight      Price
count  8.000000   8.000000
mean   4.812500  47.608750
std    1.730762  13.653949
min    2.000000  20.000000
25%    3.750000  46.250000
50%    5.000000  50.435000
75%    6.125000  56.250000
max    7.000000  60.000000

In [8]:
mean_x

np.float64(4.8125)

In [9]:
mean_y

np.float64(47.60875)

In [10]:
dev_x = x-mean_x
dev_y = y-mean_y
m = np.sum(dev_x*dev_y)/np.sum(dev_x**2)
c=mean_y-m*mean_x

print("m",m)
print("c",c)

m 2.5141281669150524
c 35.50950819672131

In [11]:
m*6.5+c

np.float64(51.85134128166915)

In [12]:
df['Predicted_Price'] = m * df['Weight'] + c

In [13]:
df.describe()

         Weight      Price  Predicted_Price
count  8.000000   8.000000         8.000000
mean   4.812500  47.608750        47.608750
std    1.730762  13.653949         4.351356
min    2.000000  20.000000        40.537765
25%    3.750000  46.250000        44.937489
50%    5.000000  50.435000        48.080149
75%    6.125000  56.250000        50.908543
max    7.000000  60.000000        53.108405

<h3> Task 02:
 Compute the residuals for each data point.

In [17]:
df['Residual'] = df['Price'] - df['Predicted_Price']
df

   Weight  Price  Predicted_Price   Residual
0     2.0  35.00        40.537765  -5.537765
1     4.0  60.00        45.566021  14.433979
2     5.0  20.00        48.080149 -28.080149
3     3.0  50.00        43.051893   6.948107
4     6.0  50.00        50.594277  -0.594277
5     5.0  55.00        48.080149   6.919851
6     7.0  60.00        53.108405   6.891595
7     6.5  50.87        51.851341  -0.981341

In [19]:
df.describe()

         Weight      Price  Predicted_Price      Residual
count  8.000000   8.000000         8.000000  8.000000e+00
mean   4.812500  47.608750        47.608750 -1.776357e-15
std    1.730762  13.653949         4.351356  1.294203e+01
min    2.000000  20.000000        40.537765 -2.808015e+01
25%    3.750000  46.250000        44.937489 -2.120447e+00
50%    5.000000  50.435000        48.080149  3.148659e+00
75%    6.125000  56.250000        50.908543  6.926915e+00
max    7.000000  60.000000        53.108405  1.443398e+01

<h3> Task 03:
 Calculate both the Mean Squared Error (MSE) and Mean Absolute Error (MAE)

In [20]:
MSE = (df['Residual'] ** 2).mean()

In [21]:
MSE

np.float64(146.5590205663189)

In [25]:
MAE = df['Residual'].abs().mean()

In [26]:
MAE

np.float64(8.798383010432191)

<h3> Final Task:
 Generate an Excel file for the given dataset. Utilize Python for all the calculations

In [27]:
df=pd.DataFrame(df)
df

   Weight  Price  Predicted_Price   Residual
0     2.0  35.00        40.537765  -5.537765
1     4.0  60.00        45.566021  14.433979
2     5.0  20.00        48.080149 -28.080149
3     3.0  50.00        43.051893   6.948107
4     6.0  50.00        50.594277  -0.594277
5     5.0  55.00        48.080149   6.919851
6     7.0  60.00        53.108405   6.891595
7     6.5  50.87        51.851341  -0.981341